name: Build FFmpegMediaPlayer APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2
        ndk: 25.2.9519653

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Clean build
      run: ./gradlew clean

    - name: Build Release APK
      run: ./gradlew :fmp-demo:assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: FMPDemo-release.apk
        path: fmp-demo/build/outputs/apk/release/fmp-demo-release.apk

    - name: Build Debug APK
      run: ./gradlew :fmp-demo:assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: FMPDemo-debug.apk
        path: fmp-demo/build/outputs/apk/debug/fmp-demo-debug.apk
