name: Build FFmpegMediaPlayer APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build Release APK
      run: ./gradlew :fmp-demo:assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: FMPDemo-release.apk
        path: fmp-demo/build/outputs/apk/release/fmp-demo-release.apk

    - name: Build Debug APK
      run: ./gradlew :fmp-demo:assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: FMPDemo-debug.apk
        path: fmp-demo/build/outputs/apk/debug/fmp-demo-debug.apk
