name: Build FFmpegMediaPlayer APK
on:
  push:
    branches:
      - master
  pull_request:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    # Кэширование только Gradle (без Android SDK)
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/modules-2
          ~/.gradle/caches/build-cache-1
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Generate local.properties
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # Предварительная загрузка зависимостей
    - name: Download dependencies
      run: ./gradlew --no-daemon dependencies
    
    # Параллельная сборка обеих версий
    - name: Build APKs
      run: |
        ./gradlew --no-daemon --parallel \
          :fmp-demo:assembleRelease \
          :fmp-demo:assembleDebug
    
    # Загрузка артефактов одним шагом
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: FMPDemo-APKs
        path: |
          fmp-demo/build/outputs/apk/release/fmp-demo-release.apk
          fmp-demo/build/outputs/apk/debug/fmp-demo-debug.apk
        retention-days: 30
